version: '3'
services:

  fetcher:
    platform: linux/amd64
    depends_on:
      - selenium
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testwdio
    tty: true
    volumes:
      - ${PWD}/test.js:/suite/test.js

  selenium:
    image: selenium/standalone-chrome:4.19.1
    container_name: testselenium
    shm_size: 2G
    environment:
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=768
    ports:
      - "7905:7900"
